number_1 =int(input("Please enter the first number:"))
number_2 =int(input("Please enter the second number:"))
average = ((number_1+number_2)/300)*100
print("average of two numbers",average)
number_1 =int(input("Please enter the first number:"))
number_2 =int(input("Please enter the second number:"))
sum = ((number_1+number_2))
print("sum of two numbers is", sum)
number_1 =int(input("Please enter the first  number:"))
number_2 =int(input("Please enter the second number:"))
subbtract =((number_1-number_2))
print("difference of two numbers is", subbtract)
number_1 =int(input("Please enter the first number:"))
number_2 =int(input("Please enter the second number:"))
multiply=((number_1*number_2))
print("product of two numbers is", multiply)
number_1 =int(input("Please enter the first number:"))
number_2 =int(input("Please enter the second number:"))
divide =((number_1//number_2)/10)*5
print("quotient of two numbers is", divide)